export const INIT_ACCOUNT = "ACCOUNT/INIT"
export const ADD_NEW_NOTIFY = "ACCOUNT/ADD_NEW_NOTIFY"
export const ADD_NEW_ADDRESS = "ACCOUNT/ADD_NEW_ADDRESS"
export const ADD_NEW_INVOICE = "ACCOUNT/ADD_NEW_INVOICE"