export const ACCOUNT_REQUEST = 'account/ACCOUNT_REQUEST';
export const ACCOUNT_SUCCESS = 'account/ACCOUNT_SUCCESS';
export const ACCOUNT_FAILED = 'account/ACCOUNT_FAILED';
export const ACCOUNT_GET_LIST_INVOICE = 'account/ACCOUNT_GET_LIST_INVOICE';